#!/usr/bin/env python
# -*- Mode: Python; indent-tabs-mode: nil; c-basic-offset: 2; tab-width: 2 -*- *

import roslib; roslib.load_manifest('exercise2')
import rospy
from geometry_msgs.msg import Twist
import time

class getchUnix:
    def __init__(self):
        import tty, sys, termios # import termios now or else you'll get the Unix version on the Mac

    def __call__(self):
        import sys, tty, termios
        fd = sys.stdin.fileno()
        old_settings = termios.tcgetattr(fd)
        try:
            tty.setraw(sys.stdin.fileno())
            ch = sys.stdin.read(1)
        finally:
            termios.tcsetattr(fd, termios.TCSADRAIN, old_settings)
        return ch

pub = rospy.Publisher('move_type', Twist, queue_size = 1000)

pressed_key = " "

getch = getchUnix()

while (pressed_key != "q"):
  key = getch()
  if key != "":
    pressed_key = key
  else:
    pressed_key = " "

  if pressed_key == "y":
    pub.publish("y")
  elif pressed_key == "x":
    pub.publish("x")
  elif pressed_key == "c":
    pub.publish("c")
  elif pressed_key == "w":
    pub.publish("w")
  elif pressed_key == "a":
    pub.publish("a")
  elif pressed_key == "s":
    pub.publish("s")
  elif pressed_key == "d":
    pub.publish("d")
  else:
    pub.publish("b")

  time.sleep(0.01)

