#!/usr/bin/env python
# -*- Mode: Python; indent-tabs-mode: nil; c-basic-offset: 2; tab-width: 2 -*- *

import roslib; roslib.load_manifest('exercise2')
import rospy
from geometry_msgs.msg import Twist
import time

def execute_movement(move):

  twist = Twist()
  if move == " ":
    twist.linear.x = 0.0
    twist.angular.z = 0.0
  elif move == "w":
    twist.linear.x = 1.0
    twist.angular.z = 0.0
  elif move == "a":
    twist.linear.x = 0.0
    twist.angular.z = -1.0
  elif move == "s":
    twist.linear.x = -1.0
    twist.angular.z = 0.0
  elif move == "d":
    twist.linear.x = 0.0
    twist.angular.z = 1.0
  elif move == "y":
    twist.linear.x = 1.0
    twist.angular.z = 0.0
    pub.publish(twist)
    time.sleep(0.5)
    twist.linear.x = 0.0
    twist.angular.z = 1.0
    pub.publish(twist)
    time.sleep(0.5)
    twist.linear.x = 1.0
    twist.angular.z = 0.0
    pub.publish(twist)
    time.sleep(0.5)
    twist.linear.x = 0.0
    twist.angular.z = 1.0
    pub.publish(twist)
    time.sleep(0.5)
  elif move == "x":
    twist.linear.x = 0.0
    twist.angular.z = 1.0
    pub.publish(twist)
    time.sleep(2.0)
    twist.linear.x = 0.0
    twist.angular.z = -1.0
    pub.publish(twist)
    time.sleep(2.0)   
  elif move == "x":
    for i in range(5):
      twist.linear.x = 0.1
      twist.angular.z = 1.0
      pub.publish(twist)
      time.sleep(0.3)
      twist.linear.x = 0.1
      twist.angular.z = -1.0
      pub.publish(twist)
      time.sleep(0.3)
  else:
    twist.linear.x = 0.0
    twist.angular.z = 0.0

  pub.publish(twist)

def movement():

  pub = rospy.Publisher('cmd_vel', Twist, queue_size = 1000)
  # For the turtle simulation map the topic to /turtle1/cmd_vel
  # For the turtlebot simulation and Turtlebot map the topic to /cmd_vel_mux/input/navi
  rospy.init_node('movement')

  r = rospy.Rate(1)

  step = 0.0
  while not rospy.is_shutdown():
    execute_movement(step)
    
    step = step + 1.0
    r.sleep()

if __name__ == '__main__':
    movement()
